config/routes.rb
RpSkypool::Application.routes.draw do

  resources :home

  root 'home#index'
  get '/contact' => 'home#contact_us'
  get '/about_us' => 'home#about_us'
  get '/gallery' => 'home#photo_gallery'
  get '/products' => 'home#products'
  get '/services' => 'home#services'

  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def create
     @contact = Contact.create(contact_params)
    if @contact.save
      UserMailer.customer_info(@contact).deliver!
      flash[:notice] = "Successfully created plan"
    else
      flash[:error] = "Error while sending contacts, please try again"
    end
    redirect_to home_index_path
  end


  private

  # Never trust parameters from the scary internet, only allow the white list through.  , , :recurring
  def contact_params
    params.required(:contact).permit(:name, :email, :phone, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
    
  end

  def services
    
  end

  def contact_us
    @contact = Contact.new
  end

  def photo_gallery
    
  end
  
  def products

  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about_us.html.erb
<div class="container">

  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <hr>
        <h2 class="intro-text text-center">About
          <strong>RP Skypool</strong>
        </h2>
        <hr>
      </div>
      <div class="col-md-6">
        <img class="img-responsive img-border-left" src="../../assets/slide-2.jpg" alt=""/>
      </div>
      <div class="col-md-6">
        <p>RP Skypools are custom residential and commercial pool builders from across in the South India. Call us for a free consultation about pools.</p>
        <p>Understanding the importance of keeping abreast of the latest design trends and pool and spa technology, Master Pools Guild members are committed to continuing education and adhere to the industry’s best practices.</p>
        <p>Understanding the importance of keeping abreast of the latest design trends and pool and spa technology, Master Pools Guild members are committed to continuing education and adhere to the industry’s best practices.</p>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>

  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <hr>
        <h2 class="intro-text text-center">Our
          <strong>Team</strong>
        </h2>
        <hr>
      </div>
      <div class="col-sm-4 text-center">
        <img class="img-responsive" src="http://placehold.it/750x450" alt=""/>
        <h3>Pradeep
          <small>CEO</small>
        </h3>
      </div>
      <div class="col-sm-4 text-center">
        <img class="img-responsive" src="http://placehold.it/750x450" alt=""/>
        <h3>Rateesh
          <small>Civil Engineer</small>
        </h3>
      </div>
      <div class="col-sm-4 text-center">
        <img class="img-responsive" src="http://placehold.it/750x450" alt=""/>
        <h3>Sandhya
          <small>MD</small>
        </h3>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>

</div>
<!-- /.container -->

app/views/home/contact_us.html.erb
<div class="container">

  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <hr/>
        <h2 class="intro-text text-center">Contact
          <strong>RP Skypool</strong>
        </h2>
        <hr/>
      </div>
      <div class="col-md-8">
        <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <hr/>
        <h2 class="intro-text text-center">Contact
          <strong>form</strong>
        </h2>
        <hr/>
        <p>If you want any support or any thing need to clarify please fill the details to contact us.</p>
        <%= form_for @contact do |f| %>
          <div class="row">
            <div class="form-group col-lg-4">
              <label>Name</label>
              <%= f.text_field 'name', class: "form-control" %>
              </div>
              <div class="form-group col-lg-4">
                <label>Email Address</label>
                <%= f.text_field 'email', class: "form-control" %>
                </div>
                <div class="form-group col-lg-4">
                  <label>Phone Number</label>
                  <%= f.text_field 'phone', class: "form-control" %>
                  </div>
                  <div class="clearfix"></div>
                  <div class="form-group col-lg-12">
                    <label>Message</label>
                    <%= f.text_area 'message', class: "form-control", :rows=>"6" %>
                    </div>
                    <div class="form-group col-lg-12">
                      <%= f.submit "Submit", class: "btn btn-default" %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>

        <!-- Embedded Google Map using an iframe - to select your location find it on Google maps and paste the link as the iframe src. If you want to use the Google Maps API instead then have at it! -->
        <%#*<iframe width="100%" height="550" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed"></iframe>%>
      </div>
      <div class="col-md-4">
        <h4>Head Office Bangalore</h4>
        <p>Call us:
          <strong>+9180 65302828</strong><br />
          <strong>+91 9916628280</strong><br />
          <strong>+91 9916628281</strong>
        </p>
        <p>Email us:
          <strong><a href="mailto:rpskypool@gmail.com">rpskypool@gmail.com</a></strong>
        </p>
        <p>Reach us :
          <strong>#422, Railway parallel road,
            <br />NGEF Layout, Sadanadanagar,
            <br />Bangalore-560038</strong>
        </p>
      </div>
      <div class="col-md-4">
        <h4>Branch Office Thrissur(Kerala)</h4>
        <p>
          <strong>+91 7025170225</strong><br />
          <strong>+91 7025673223</strong>
        </p>
        <p>
          <strong><a href="mailto:rpskypool.kl@gmail.com">rpskypool.kl@gmail.com</a></strong>
        </p>
        <p>
          <strong>#556,Nooluvally, Chembuchira post,
            <br /> Kodakarak via, Thrissur-680684</strong>
        </p>
      </div>
      <div class="col-md-4">
        <h4>Branch Office Trivandrum</h4>
        <p>
          <strong>+91 7025170225</strong><br />
          <strong>+91 9562050499</strong><br />
         </p>
        <p>
          <strong><a href="mailto:rpskypool.tvm@gmail.com">rpskypool.tvm@gmail.com</a></strong>
        </p>
        <p>
          <strong>#3/2233, Near Panayil Bakers,
            <br />Kulathoor, Kazhakkuttam,
            <br />Trivandrum-695583</strong>
        </p>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>

  <%#*<div class="row">%>
    <%#*<div class="box">%>
      <%#*<div class="col-lg-12">%>
        <%#*<hr/>%>
        <%#*<h2 class="intro-text text-center">Contact%>
          <%#*<strong>form</strong>%>
        <%#*</h2>%>
        <%#*<hr/>%>
        <%#*<p>If you want any support or any thing need to clarify please fill the details to contact us.</p>%>
        <%#= form_for @contact do |f| %>
          <%#*<div class="row">%>
            <%#*<div class="form-group col-lg-4">%>
              <%#*<label>Name</label>%>
              <%#= f.text_field 'name', class: "form-control" %>
              <%#*</div>%>
              <%#*<div class="form-group col-lg-4">%>
                <%#*<label>Email Address</label>%>
                <%#= f.text_field 'email', class: "form-control" %>
                <%#*</div>%>
                <%#*<div class="form-group col-lg-4">%>
                  <%#*<label>Phone Number</label>%>
                  <%#= f.text_field 'phone', class: "form-control" %>
                  <%#*</div>%>
                  <%#*<div class="clearfix"></div>%>
                  <%#*<div class="form-group col-lg-12">%>
                    <%#*<label>Message</label>%>
                    <%#= f.text_area 'message', class: "form-control", :rows=>"6" %>
                    <%#*</div>%>
                    <%#*<div class="form-group col-lg-12">%>
                      <%#= f.submit "Submit", class: "btn btn-default" %>
                      <%#*</div>%>
                    <%#*</div>%>
                  <%# end %>
                <%#*</div>%>
              <%#*</div>%>
            <%#*</div>%>
          </div>
          <!-- /.container -->

          <script type="text/javascript">
            $(function() {
              $('#new_contact').validate({
                ignore: [],
                rules:{
                  'contact[name]':
                    {
                    required: true
                  },
                  'contact[email]':{
                    required: true,
                    email:true
                  },
                  'contact[phone]':{
                    required: true,
                    number: true,
                    minlength:10
                  },
                  'contact[message]':{
                    required: true
                  }
                },
                messages:{
                  'contact[name]':{
                    required: ("Please enter the name.")
                  },
                  'contact[email]':{
                    required: "Please enter the email.",
                    email: "Please enter valid email."
                  },
                  'contact[phone]':{
                    required: "Please enter the mobile number.",
                    number: "Please enter only numbers.",
                    minlength: "Please enter the correct mobile number"

                  },
                  'contact[message]':{
                    required: "Please enter the message."
                  }
                }
              });
            });
          </script>

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div class="box">
      <div class="col-lg-12 text-center">
        <div id="carousel-example-generic" class="carousel slide">
          <!-- Indicators -->
          <ol class="carousel-indicators hidden-xs">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            <li data-target="#carousel-example-generic" data-slide-to="4"></li>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <div class="item active">
              <img class="img-responsive img-full" src="../../assets/pool1.jpeg" alt=""/>
            </div>
            <div class="item">
              <img class="img-responsive img-full" src="../../assets/pool2.jpeg" alt=""/>
            </div>
            <div class="item">
              <img class="img-responsive img-full" src="../../assets/pool3.jpeg" alt=""/>
            </div>
            <div class="item">
              <img class="img-responsive img-full" src="../../assets/pool4.jpeg" alt=""/>
            </div>
            <div class="item">
              <img class="img-responsive img-full" src="../../assets/pool23_1.jpg" alt=""/>
            </div>
          </div>

          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
            <span class="icon-prev"></span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
            <span class="icon-next"></span>
          </a>
        </div>
        <h2 class="brand-before">
          <small>Welcome to</small>
        </h2>
        <h1 class="brand-name">RP Skypool</h1>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <hr/>
        <h2 class="intro-text text-center">
          <strong>About Us</strong>
        </h2>
        <hr/>
        <img class="img-responsive img-border img-left" src="../../assets/intro-pic.jpg" alt=""/>
        <hr class="visible-xs"/>
        <p>RP Skypool a premium segment pool and spa building company provides complete solutions for Pools, Spa, and Wellness industry with a rich engineering background, the team RP Skypool can offer their services right from conceptualization to completion.</p>
        <p>The pool and spa's are designed keeping in mind the current trends of industry and every installation is equipped with top of the line products sourced from all over the world. Each product used is tested by quality engineer and certified before use. </p>
        <p>In addition to general pools we also specialize in infinity edge pools, climate control pools, natural pool and salt water pools.</p>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <hr/>
        <h2 class="intro-text text-center">
          <strong>Vision</strong>
        </h2>
        <hr/>
        <p>Company Vision is to provide by engineering and integrating our technology and be a leader & provide unparalleled quality engineering solutions and services to our clients across India & the globe in the areas of Water & Environment</p>
      </div>
    </div>
  </div>



  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <hr/>
        <h2 class="intro-text text-center">
          <strong>Mission</strong>
        </h2>
        <hr/>
        <p>The whole of our organisation works to deliver safely, trust and innovative solutions to our customers. </p>
        <p>We seek to progress together in constructing long-lasting relationships based on respect and mutual benefit. </p>
        <p>We are committed to future generations by boosting the responsible use of water and by applying rigorous criteria for sustainability</p>
      </div>
    </div>
  </div>

  
</div>
<!-- /.container -->

app/views/home/photo_gallery.html.erb
<div class="row">
    <div class="box">
      <div class="col-lg-12 text-center">
        <div id="carousel-example-generic" class="carousel slide">
          <!-- Indicators -->
          <ol class="carousel-indicators hidden-xs">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            <li data-target="#carousel-example-generic" data-slide-to="4"></li>
            <li data-target="#carousel-example-generic" data-slide-to="5"></li>
            <li data-target="#carousel-example-generic" data-slide-to="6"</li>
            <li data-target="#carousel-example-generic" data-slide-to="7"></li>
            <li data-target="#carousel-example-generic" data-slide-to="8"></li
            <li data-target="#carousel-example-generic" data-slide-to="9"></li>
            <li data-target="#carousel-example-generic" data-slide-to="10"></li>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <div class="item active">
              <img class="img-responsive img-full" src="../../assets/pool1.jpeg" alt=""/>
            </div>
            <div class="item">
              <img class="img-responsive img-full" src="../../assets/pool2.jpeg" alt=""/>
            </div>
            <div class="item">
              <img class="img-responsive img-full" src="../../assets/pool3.jpeg" alt=""/>
            </div>
            <div class="item">
              <img class="img-responsive img-full" src="../../assets/pool4.jpeg" alt=""/>
            </div>
            <div class="item">
              <img class="img-responsive img-full" src="../../assets/pool23_1.jpg" alt=""/>
            </div>
             <div class="item">
              <img class="img-responsive img-full" src="../../assets/pool2.jpeg" alt=""/>
            </div>
            <div class="item">
              <img class="img-responsive img-full" src="../../assets/pool3.jpeg" alt=""/>
            </div>
            <div class="item">
              <img class="img-responsive img-full" src="../../assets/pool4.jpeg" alt=""/>
            </div>
            <div class="item">
              <img class="img-responsive img-full" src="../../assets/pool23_1.jpg" alt=""/>
            </div>
            <div class="item">
              <img class="img-responsive img-full" src="../../assets/pool23_1.jpg" alt=""/>
            </div>
            <div class="item">
              <img class="img-responsive img-full" src="../../assets/pool23_1.jpg" alt=""/>
            </div>

          </div>

          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
            <span class="icon-prev"></span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
            <span class="icon-next"></span>
          </a>
        </div>
        <%#*<h2 class="brand-before">%>
          <%#*<small>Welcome to</small>%>
        <%#*</h2>%>
        <%#*<h1 class="brand-name">RP Skypool</h1>%>
        <%#*<hr class="tagline-divider"/>%>
        <%#*<h2>%>
          <%#*<small>By%>
            <%#*<strong>Rateesh&nbsp;& &nbspPradeep</strong>%>
          <%#*</small>%>
        <%#*</h2>%>
      </div>
    </div>
  </div>

app/views/home/services.html.erb
<div class="container">
  <div class="row">
    <div class="box">
      <div class="col-lg-12">
        <hr/>
        <h2 class="intro-text text-center">
          <strong>Our Services</strong>
        </h2>
        <hr />
      </div>
      <div class="col-md-12">
        <div class ="services">
          <ul>
            <ul class="list-unstyled">
              <li>Design and construction of all types of swimming pools</li>
              <li>Water features & Fountains</li>
              <li>Jaccuzzi/spa</li>
              <li>Steam Room/Sauna Room</li>
              <li>Supply and installation swimming pool equipment, tiles and pool chemicals.</li>
              <li>Pool trouble shooting and maintenance and services.</li>
              <li>Renovation of old swimming pools.</li>
              <li>Plumbing and sanitary engineers and contractors </li>
              <li>Environmental & water management solutions</li>
              <li>Dealer for FRP and liner pools(Ready made)</li>
            </ul>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <title>RP Skypools</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="RP Skypool" content="width=device-width, initial-scale=1"/>
    <meta name="description" content="Swimming pool construction company"/>
    <meta name="author" content="Pradeep"/>
    <meta name="keywords" content="rpskypool, sky pool, skypool, swimming pool, pool, swimming" />


    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css"/>
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css"/>
    <%= stylesheet_link_tag    "application", "bootstrap.min", "styles", "jquery.notifyBar", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "bootstrap.min", "jquery.validate", "jquery.notifyBar", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="brand">
      <img class="img-responsive logo-img" src="../../assets/logo.jpg" alt=""/>
    </div>
    <div class="address-bar"></div>
    <!-- Navigation -->
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
        <a class="navbar-brand" href="<%= home_index_path %>">RP Skypool</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <a href="<%= home_index_path %>">Home</a>
          </li>
          <li>
            <a href="<%= products_path %>">Products</a>
          </li>
          <li>
            <a href="<%= services_path %>">Services</a>
          </li>
          <li>
            <a href="<%= gallery_path %>">Photo Gallery</a>
          </li>
          <li>
            <a href="<%= contact_path %>">Contact</a>
          </li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </nav>

  <%= yield %>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <p>Copyright &copy; rpskypool.com 2015</p>
        </div>
      </div>
    </div>
  </footer>
  <script type="text/javascript">
    $('.carousel').carousel({
      interval: 5000 //changes the speed
    })


    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-61644956-1', 'auto');
    ga('send', 'pageview');


  </script>
</body>
</html>





<style type="text/css">

  .logo-img{
    height: 170px;

    width: 350px;
  }

</style>